<?php

namespace GFPDF\Plugins\BulkGenerator;

use League\Flysystem\FileNotFoundException;
use League\Flysystem\Memory\MemoryAdapter;

class EnhancedMemoryAdapter extends MemoryAdapter {
	public function read( $path ) {
		if ( ! isset( $this->storage[ $path ] ) ) {
			throw new FileNotFoundException( 'Not found' );
		}

		return parent::read( $path ); // TODO: Change the autogenerated stub
	}
}