<?php

namespace GFPDF\Plugins\BulkGenerator\Model;

use GFPDF\Plugins\BulkGenerator\Exceptions\FilesystemError;
use GFPDF\Plugins\BulkGenerator\Exceptions\PdfGenerationError;
use GFPDF\Plugins\BulkGenerator\Utility\FilesystemHelper;
use League\Flysystem\Filesystem;
use League\Flysystem\Memory\MemoryAdapter;

class PdfTest extends \WP_UnitTestCase {

	protected $pdf;
	protected $filesystem;

	private $form_id;
	private $entry;

	public function setUp() {
		$this->entry = $this->create_entry();

		$this->pdf        = new Pdf( $this->entry['form_id'], '5e7bfc55b6ec9' );
		$this->pdf->fetch();
		$this->filesystem = new Filesystem( new MemoryAdapter() );

		parent::setUp(); // TODO: Change the autogenerated stub
	}

	protected function create_entry() {
		$form_id = \GFAPI::add_form( json_decode( file_get_contents( __DIR__ . '/../../json/sample.json' ), true ) );

		$entry_id = \GFAPI::add_entry( [
			'form_id'        => $form_id,
			'created_by'     => $this->factory->user->create(),
			'date_created'   => '2020-02-01 01:30:00',
			'payment_status' => 'Paid',
			'currency'       => 'USD',
			'1'              => 'Sample',
		] );

		return \GFAPI::get_entry( $entry_id );
	}

	/**
	 * @expectedException \GFPDF\Plugins\BulkGenerator\Exceptions\InvalidPdfId
	 */
	public function test_fetch_exemption() {
		$this->pdf->fetch();
	}

	public function test_has_setting() {
		$this->assertTrue( $this->pdf->has_setting( 'name' ) );
		$this->assertFalse( $this->pdf->has_setting( 'test' ) );
		$this->assertTrue( $this->pdf->has_setting( 'filename' ) );
		$this->assertFalse( $this->pdf->has_setting( 'dummy_test' ) );
		$this->assertTrue( $this->pdf->has_setting( 'name' ) );
		$this->assertFalse( $this->pdf->has_setting( 'test' ) );
		$this->assertTrue( $this->pdf->has_setting( 'filename' ) );
		$this->assertFalse( $this->pdf->has_setting( 'dummy_test' ) );
	}

	public function test_get_setting() {

	}

	public function test_get_all_settings() {

	}

	public function test_evaluate_active() {

	}

	/**
	 * @expectedException \GFPDF\Plugins\BulkGenerator\Exceptions\PdfConditionalLogicFailed
	 */
	public function test_evaluate_conditional_logic() {
		$misc = \GPDFAPI::get_misc_class();

		$this->pdf->evaluate_conditional_logic( $this->entry );
		//$item = $misc->evaluate_conditional_logic( $this->pdf->get_setting( 'conditionalLogic' ), $data );
		//$this->assertSame( 'null', $data->settings['conditionalLogic'] );
	}


	/**
	 * @expectedException PdfGenerationError
	 * @throws \GFPDF\Plugins\BulkGenerator\Exceptions\InvalidPdfId
	 */
	public function test_generate_get_path() {
		$pdf_path = 'Zadani.pdf';

		$this->config();
		$this->pdf->fetch()
		          ->generate( $this->entry['id'] );
		$this->assertSame( $pdf_path, substr( strrchr( $this->pdf->get_path(), "/" ), 1 ) );
	}

	public function test_get_path() {

	}

	/**
	 * @expectedException PdfGenerationError
	 */
	public function test_put() {
		$this->config();
		$this->pdf->fetch()
		          ->generate( $this->entry['id'] );
		$this->assertNotEmpty( $this->pdf->put( $this->filesystem, '\'/\'' ) );
	}


	public function config() {
		add_filter( 'gfpdf_mpdf_class_config', function( $config ) {
			$config['mode']          = 'c';
			$config['biDirectional'] = false;

			return $config;
		} );
	}

}
